### ISSUE TITLE
Question about Hardcoded urls?

### ISSUE THREAD

**Issue by erdemozveren** [mrwyndham/pocketbase-stripe#3]
Hi, in main.go file in multiple places there are hardcoded urls for "sign365.com.au" and im not a GO person but seems like it doesnt respect "HOST" env key,is this a bug or am i missing something can you enlighten me please.

**Comment by erdemozveren** [comment]
Also noticed "customer" table does not exists on pb_schema.json

**Comment by mrwyndham** [comment]
Heya Erdemoz - I have just updated the repo. I have been working on fastpocket.dev and have been making most of the changes there. Have just sent those changes downstream now. Take a look again and tell me what you think

**Comment by erdemozveren** [comment]
Hello Again, Thank you for updates.I tested out little bit and these are my observations as _not a GO developer_;
As far as i tested out all stripe data inserted/updated correctly. (except adress columns)

- Organisation table seems unreleated
- Users table seems missing columns : "billing_address","payment_method"

- this part seems unreleated for this extension
```
app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.GET("/goext/:name", func(c echo.Context) error {
			name := c.PathParam("name")

			return c.JSON(http.StatusOK, map[string]string{"message": "Hello " + name})
		} /* optional middlewares */)

		return nil
	})
	jsvm.MustRegister(app, jsvm.Config{
		HooksWatch:    true,
		HooksPoolSize: 25,
	})
```

- When i checkout successfully with test mode i got this error on "checkout.session.completed" event and i found its because of some session values are nil (like session.Subscription.Customer.ID) but it could be my problem because i changed stripe version to v78 
```
event : checkout.session.completed
ERROR POST /stripe 
└─ Something went wrong while processing your request.
   └─ [PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 44 [running]:
```
Thank you again for this extension.

**Comment by mrwyndham** [comment]
Loved this. I will make sure to update those accordingly in the bootstrap for pocketbase. Thanks again for taking the time to look at this stuff. Makes me happy to know there are people like you out there!
