### ISSUE TITLE
Merchant of record 

### ISSUE THREAD

**Issue by gedw99** [mrwyndham/pocketbase-stripe#5]
https://github.com/NdoleStudio/lemonsqueezy-go

Stripe is fine but for EU you end up in sales tax hell . 

This golang API looks decent 

also docs are good 

https://docs.lemonsqueezy.com/api

pricing is ok.

The main thing will be the web hooks for them .

the PB hooks for when a product is sold and sent to them is easy.

**Comment by mrwyndham** [comment]
It may be something I look at in the future as a downstream from fastpocket.dev but for now this is a planned feature in fastpocket.dev

**Comment by gedw99** [comment]
For any other devs there is https://github.com/NdoleStudio/lemonsqueezy-go
